### ISSUE TITLE
mouse events on canvas - bounding box - crop

### ISSUE THREAD

**Issue by bikedel** [ajstarks/fc#1]
Hello

Is it possible to load an image and let the user click around an object in the image and then draw a rectangle around the object as in a bounding box or crop the image accordingly?

**Comment by ajstarks** [comment]
I suspect this is possible.  fc wraps the standard fyne components, so it should work.

**Comment by bikedel** [comment]
I am still trying to work out how to get mouse events from the standard canvas fyne component.

Any chance you could point me to some code that does this or maybe just a hint.

Thanks.

ok not to worry I was pointed in the right direction....as below


To draw around an object you will need another object, perhaps a rectangle with StrokeColor and StrokeWidth. Add both items to a container.NewMax and they will draw one over the other at the same size.

Mousse events are sent to widgets that are under them. To get a mouse event directly either extend or implement a widget and add the appropriate handlers. https://developer.fyne.io/tutorial/extending-widgets

A canvas is the drawing area, it cannot be inserted into another canvas.
By canvasObjects can be drawn over each other using a Container or Widget.
