### ISSUE TITLE
can I moditicate?

### ISSUE THREAD

**Issue by MatejMagat305** [ajstarks/fc#3]
I would like to ask you like https://github.com/fyne-io/fyne/issues/2924, do you plan or would you allow me make some modifications to make "only" CanvasObject to integrate to fyne?

_Originally posted by @MatejMagat305 in https://github.com/ajstarks/fc/issues/2#issuecomment-1101225483_

you will mind, that I modificate your library and maybe give pull request to fyne?

**Comment by ajstarks** [comment]
feel free to fork and add your changes.

**Comment by MatejMagat305** [comment]
THANK
